version: "3.7"

services:
  go-app:
    container_name: go-app
    # image: francescoxx/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=rohan dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: rohan
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
