version: "3.7"

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "user=postgres password=rohan dbname=postgres host:go_db sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    restart: always
    volumes:
      - ./ASSETS:/app/ASSETS

    networks:
      - fullstack
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: rohan
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack

volumes:
  pgdata: {}

networks:
  fullstack:
    driver: bridge
